### ISSUE TITLE
Fail to getVersionInfo for package, where sideEffects is no boolean

### ISSUE THREAD

**Issue by barclay-reg** [OrienteerBAP/JNPM#11]
Trying to load VersionInfo for https://registry.npmjs.org/@angular%2Fcommon/11.2.14 fails

Using jnpm 1.1
````
VersionInfo vueVersion = JNPMService.instance().getVersionInfo("@angular/common", "11.2.14");
````

brings the following exception

````
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `boolean` out of START_ARRAY token
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 784] (through reference chain: org.orienteer.jnpm.dm.VersionInfo["sideEffects"])

	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at org.orienteer.jnpm.JNPMService.getVersionInfo(JNPMService.java:112)
````

Analysis shows, that JSON response from https://registry.npmjs.org/@angular%2Fcommon/11.2.14 contains `sideEffects` as array, which does not fit to `org.orienteer.jnpm.dm.VersionInfo`

````
....
,
  "sideEffects": [
    "**/global/*.js",
    "**/closure-locale.*"
  ],
...
````

**Comment by PhantomYdn** [comment]
Thank you, @barclay-reg , for initial review!
Seems that it does require code-change. Please give me sometime today to get that fixed. Will update this ticket once done.

**Comment by PhantomYdn** [comment]
@barclay-reg , fixed. Please check from your end. Make sure that you are using 1.2-SNAPSHOT

**Comment by barclay-reg** [comment]
@PhantomYdn many thanks - works like a charm

**Comment by barclay-reg** [comment]
@PhantomYdn do you have any idea, when this will be released?
I see, that there still is one issue open for 1.2 - but as no progress was made there (and this is not as trivial as this fix) I'm wondering if that issue can be postponed to a 1.3

**Comment by PhantomYdn** [comment]
@barclay-reg , if you are fine with provided functionality and no changes are needed by now: it's not a problem I can release bug-fixing version **1.1.1**

**Comment by barclay-reg** [comment]
yes - this would be fine

**Comment by PhantomYdn** [comment]
Release 1.2 has been published:
https://github.com/OrienteerBAP/JNPM/releases/tag/v1.2
