### ISSUE TITLE
Update Jackson to get rid of deprecation messages

### ISSUE THREAD

**Issue by lppedd** [OrienteerBAP/JNPM#23]
Thanks for the library!  
I'm using it in a custom Gradle task, and every execution I receive deprecation messages from Jackson:

> PropertyNamingStrategy.SnakeCaseStrategy is used but it has been deprecated due to risk of deadlock. Consider using PropertyNamingStrategies.SnakeCaseStrategy instead. See https://github.com/FasterXML/jackson-databind/issues/2715 for more details.

It would be cool to update it, or remove usages of deprecated symbols.  

If you don't have the time, let me know and I'll do it.

**Comment by PhantomYdn** [comment]
Makes perfect sense. Thank you!
Are you fine with using SNAPSHOT version for some period time or prefer some intermediate minor version?

**Comment by PhantomYdn** [comment]
@lppedd , just pushed changes to github and mvn central as SNAPSHOT
Thank you for awaiting!

**Comment by lppedd** [comment]
@PhantomYdn thanks! I can confirm it works ok without any deprecation message now.
