### ISSUE TITLE
CDNServlet does not work with scopes

### ISSUE THREAD

**Issue by Enerccio** [OrienteerBAP/JNPM#24]
I had to hack it around with my custom servlet that will parse @something/something@version correctly by doing this:

    private static final String PATH_PATTERN = "/([^/]*)/([^/@]*)@?([^/]*)/(.*)";
    private static final Pattern PATH_REGEXP = Pattern.compile(PATH_PATTERN);

    CDNRequest request;
    Matcher m = PATH_REGEXP.matcher(req.getPathInfo());
    if (m.matches()  && m.group(1).startsWith("@")) {
        request = new CDNRequest(m.group(1) + "/" + m.group(2), m.group(3), m.group(4));
    } else {
        request = CDNRequest.valueOf(req.getPathInfo());
    }

**Comment by PhantomYdn** [comment]
@Enerccio , pushed to mvn as snapshot. Please check.
